[tool.poetry]
name = "u-net-pytorch"
version = "0.1.0"
description = ""
authors = ["Igor Martins <igor.mart.san@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
